### ISSUE TITLE
Possible support for Macewan University?

### ISSUE THREAD

**Issue by ttamre** [Step7750/ScheduleStorm#1]
http://www.macewan.ca/wcm/

**Comment by Step7750** [comment]
I found the classes here: http://cs-public.www.macewan.ca/psc/public/WEBADVSR/SA/c/COMMUNITY_ACCESS.CLASS_SEARCH.GBL

After testing it out, it is extremely slow and would probably take 30min+ to scrape all class data. Getting the classes for each course requires a separate request. Do you happen to have a faster non-login source of class data for it?

**Comment by ttamre** [comment]
Unfortunately, I can't find a faster non-login source. I don't think there is one, but if I do find one I'll post it in this issue thread.

**Comment by Step7750** [comment]
If you'd like to, you're welcome to add Macewan to the server repo, here are some docs: https://github.com/Step7750/ScheduleStorm_Server#how-to-add-your-university.

I'll look into it, but an admin from there might be able to give a better source of data (without overloading the existing infrastructure).
