### ISSUE TITLE
Incomplete scheduling of classes with variable time slots

### ISSUE THREAD

**Issue by kylehennig** [Step7750/ScheduleStorm#10]
For the University of Alberta Fall 2018 Semester:
Japan 301 is listed as MW 9:00 AM-10:20 AM. This is not the case, as Japan 301 also runs on Friday from 9:00 AM-9:50 AM. Perhaps this is due to the time slot on Friday being different from that of Monday and Wednesday's lectures?

**Comment by Perplex** [comment]
The fix has been pushed to the server and after the server updates you should be able to see the changes on the site.
