### ISSUE TITLE
Multiple Classes for the Same Subject

### ISSUE THREAD

**Issue by MrShikky** [Step7750/ScheduleStorm#12]
Hey guys, 

I'm trying to add ME 303 for the Spring 2018 term at UWaterloo, and I think the program is only registering one of the timeslots for lectures (the Friday one)

**Comment by Perplex** [comment]
Thank you for opening this issue, as I am not a UWaterloo student its hard for me to spot these mistakes. I hope this is the only bug on the UWaterloo side but if not please feel free to open another issue so I can fix it as soon as possible.

**Comment by MrShikky** [comment]
Anytime! This tool is drastically changing my current (horrible) method of organizing my schedule. So far ScheduleStorm has been nothing but pleasure for me as the End User.
I’ll keep my eye out for any more possible issues - I’m always happy to help.

P.s. are you guys thinking of making a mobile app?

**Comment by Perplex** [comment]
Currently me and Step are not thinking about that but even if we wanted to we do not have the expertise to build a mobile app that would satisfy the needs of our users on such small screens.
