### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by ahoskins** [Step7750/ScheduleStorm#13]
Hey Stepan! This is very cool! I created https://github.com/ahoskins/winston many years ago when I was a student at UAlberta. It's awesome to see the next evolution of this project, and generalizing the implementation to support many schools.

As students, we can have more power and impact on large institutions than we may think...keep up the great work &mdash; I'm excited where this project can go.

**Comment by Step7750** [comment]
Hey Andrew, thanks for the kind words! We got lots of inspiration from Winston so it's pretty great to see your opinion on it!
