### ISSUE TITLE
Lab/ Class detection

### ISSUE THREAD

**Issue by rosenberrr** [Step7750/ScheduleStorm#14]
Hey guys, 

As I am attempting to place 5 classes on a schedule my labs are being counted as a class, and therefore only allowing 4 total classes to show up on my timetable. Is there any way you can change this to group the lab and lecture for said class together to count as one or allow for 6 or 7 classes to be placed in a time table?

Thank you for your time and I look forwards to hearing from you!

**Comment by Perplex** [comment]
Which university are you having this problem with?

**Comment by rosenberrr** [comment]
University of Alberta

**Comment by Step7750** [comment]
Please use the "Copy Schedule to Clipboard" option so we can see what the courses are that cause this, or please give us a list of the courses you're trying to add.

![image](https://user-images.githubusercontent.com/11811793/38151929-7dfd71aa-3422-11e8-9663-75e70e3fd094.png)

**Comment by rosenberrr** [comment]
Generated by ScheduleStorm.com for University of Alberta Fall 2018

61196 | KIN 311 | LEC-A1 (61196) | N/A | VVC 2 210 | MW 09:30AM - 10:50AM | Closed
61382 | KIN 334 | LEC-A1 (61382) | N/A | ECHA L1 190 | TR 08:00AM - 09:20AM | Open
61168 | KIN 335 | LEC-A1 (61168) | N/A | VVC 2 210 | TR 11:00AM - 12:20PM | Open
60078 | BIOCH 200 | LEC-A1 (60078) | N/A | CCIS 1 440 | MWF 11:00AM - 11:50AM | Open
69620 | INT D 410A | SEM-C11 (69620) | N/A | N/A | N/A | Closed
61348 | KIN 335 | LAB-D3 (61348) | N/A | ED N1 126 | W 02:00PM - 02:50PM | Open
61284 | KIN 311 | LAB-D3 (61284) | N/A | VVC 4 291 | W 12:00PM - 01:50PM | Closed


I just realized that the issue is that Int D 410a isn’t showing up on the schedule, not that a lab is registering. And that isn’t your issue, the university hasn’t released the times yet. Sorry about that!

**Comment by Step7750** [comment]
No problem.

It'd be more clear if there was a UI component indicating classes that can't be displayed on the schedule.
