### ISSUE TITLE
Missing Course?

### ISSUE THREAD

**Issue by Gethatbread** [Step7750/ScheduleStorm#9]
I tried to find the Math 300 (A & B) courses for University of Alberta on Schedule Storm, (it exists on the University site) but the search did not return any results. Anyone know how this can be solved?

**Comment by Perplex** [comment]
Im not seeing Math 300A or 300B in the course catalog on Bear Tracks, but I do see Math 300 and that is showing up on Schedule Storm.

**Comment by Gethatbread** [comment]
yes, you're right that it exists, I saw it for fall 2018
I forgot to specify, I was looking at the spring/summer 2018 terms.

**Comment by Perplex** [comment]
Ok yup theres definitely something wrong with the scraper. I'll take a look.

**Comment by Perplex** [comment]
Issue fixed, the server will take a while to update
